version: '3.4'

services:
  girlathon:
    image: girlathon
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
